### ISSUE TITLE
Ansible vault stopped working

### ISSUE THREAD

**Issue by andviro** [drone-plugins/drone-ansible#16] opened 2019-03-28 22:39 UTC
Hello! 

Can you please add some cryptography library to the image? My builds suddenly started to fail with: `ERROR! ansible-vault requires either the cryptography library (preferred) or pycrypto in order to function.`

**Comment by tboerger** [comment] 2019-03-29 10:27
Feel free to create a pull request which adds it to all Dockerfiles within the docker folder.

**Comment by xoxys** [comment] 2019-03-29 10:43
Normally this should work while we install ansible with pip in the dockerfiles. Because `cryptography` is a required Python dependency for ansible and will be installed anyway. 

So I think there is something else "wrong".

**Comment by xoxys** [comment] 2019-03-29 10:45
@tboerger maybe `cryptography` is also part of a package we are removing after `pip install ansible` in the dockerfile

**Comment by tboerger** [comment] 2019-03-29 12:51
We are just removing dev packages, and we also did that before.

**Comment by andviro** [comment] 2019-03-29 20:57
It seems that removal of `libressl-dev` breaks vault support somehow. I dont know how this problem never shown itself, but you can easily verify it by running `ansible-vault create` from within container. If this is ok, I can prepare a PR that fixes this.

**Comment by xoxys** [comment] 2019-03-29 21:19
So right direction :) Yes please prepare a pull request for all docker files

**Comment by andviro** [comment] 2019-03-30 09:38
please see PR #17. I'd also bumped up Ansible version to 2.7.9, if you don't mind.

**Comment by xoxys** [comment] 2019-03-31 18:08
I was able to reproduce the issue. Reinstall libressl fixed the issue as described.

**Comment by tboerger** [comment] 2019-04-01 12:14
Since #17 had been merged this can get closed :)

**Closed by tboerger** 2019-04-01 12:14 UTC
